### ISSUE TITLE
Browser testing

### ISSUE THREAD

**Issue by ibdf** [CityOfPhiladelphia/phila-ui#116]

**Comment by ibdf** [comment]
Ie11, Edge, Firefox, Chrome, Safari, Mobile browsers

**Comment by ajrothwell** [comment]
ok, I tested http://phila-ui-boilerplate-demo-site.s3-website-us-east-1.amazonaws.com/ in all of these browsers

The only issue I found was IE11, the app does not really work at all.

"Object doesn't support property or method 'includes'"
